server:
  port: 8091
  address: 0.0.0.0

spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3360}/${MYSQL_DATABASE:cards}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update